FROM alpine:3

RUN apk update && \
    apk add python3 py3-pip

RUN pip --version

RUN mkdir -p /code
WORKDIR /code

COPY . .

ENV PIPENV_VENV_IN_PROJECT=1

RUN pip install --ignore-installed distlib pipenv \
    && pipenv update \
    && pipenv sync

# Set PATH environment variable
ENV PATH="${PATH}:$(pipenv --venv)/bin"